---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by dongfeng297.
--- DateTime: 2025/1/2 下午11:51
---

if(redis.call('get' ,KEYS[1])==ARGV[1]) then
    return redis.call('del',KEYS[1])
end
return 0
